spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://192.168.1.102/sell?characterEncoding=utf-8&useSSl=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true

ribbon:
  eureka:
    enabled: true

server:
  port: 8081
